# Generated by Django 4.2.1 on 2023-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.URLField(max_length=2083),
        ),
    ]
