# Generated by Django 4.2.1 on 2023-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bundle',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
